#!/usr/bin/perl 
use Array::Utils qw(:all);

my @a = map { s/^\s+|\s$//g; $_ } `cat $ARGV[0]`;
my @b = map { s/^\s+|\s$//g; $_ } `cat $ARGV[1]`;

my @diff = array_diff(@a, @b);
for (@diff) {
    print "$_\n";
}
