#!/usr/bin/perl 

my $time = $ARGV[0];

if ($time !~ /^\d+$/) {
    usage();
    exit(1);
}

XXX($time);
exit (0);


sub XXX {
    my $time = shift;
    my ($S,$M,$H,$d,$m,$Y) = localtime($time);
    $m += 1;
    $Y += 1900;

    if ($Y > 3000) {
        $time = $time/1000;
        return XXX($time);
    }

    my $dt = sprintf("%04d-%02d-%02d %02d:%02d:%02d", $Y,$m,$d, $H,$M,$S);
    print $dt, "\n";
}

sub usage {
    print "$0 <unix_timestamp>\n";
}
